apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "springboot-api.fullname" . }}
  labels:
    {{- include "springboot-api.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://{{ .Values.mysql.host }}:{{ .Values.mysql.port }}/{{ .Values.mysql.database }}?useSSL=false&allowPublicKeyRetrieval=true
  SPRING_DATASOURCE_USERNAME: {{ .Values.mysql.username | quote }}
  SPRING_JPA_HIBERNATE_DDL_AUTO: {{ .Values.mysql.ddlAuto | quote }}
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: {{ .Values.mysql.dialect | quote }}