apiVersion: v1
kind: Secret
metadata:
  name: {{ include "springboot-api.fullname" . }}
  labels:
    {{- include "springboot-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.mysql.password | quote }}