apiVersion: v1
kind: Secret
metadata:
  name: spring-database-credentials
  namespace: tutorial-app
type: Opaque
stringData:
  datasource-username: "root"
  datasource-password: "123456"
  datasource-url: "jdbc:mysql://mysql-database:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true"