apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: tutorial-app
type: Opaque
data:
  
  mysql-root-password: MTIzNDU2  
  mysql-user: cm9vdA==  
  
---
apiVersion: v1
kind: Secret
metadata:
  name: spring-database-credentials
  namespace: tutorial-app
type: Opaque
data:
  datasource-username: cm9vdA==  
  datasource-password: MTIzNDU2  
  datasource-url: amRiYzpteXNxbDovL21zc3FsLWRhdGFiYXNlOjMzMDYvdGVzdGRiP3VzZVNTTD1mYWxzZSZhbGxvd1B1YmxpY0tleVJldHJpZXZhbD10cnVl  # jdbc:mysql://mysql-database:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true
