
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: tutorial-app
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
 
  hostPath:
    path: /var/lib/mysql-data
    type: DirectoryOrCreate
  storageClassName: local-storage

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: tutorial-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
