version: '3.9'

services:

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: testdb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    secrets:
      - mysql_root_password
  
    command: ["sh", "-c", "export MYSQL_ROOT_PASSWORD=$(cat /run/secrets/mysql_root_password) && exec docker-entrypoint.sh mysqld"]

  api:
    build:
      context: ./spring-boot-server
      dockerfile: Dockerfile
    container_name: spring-boot-api
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    secrets:
      - spring_datasource_password
 
  web:
    build:
      context: ./react-client
      dockerfile: Dockerfile
    container_name: react-frontend
    restart: unless-stopped
    ports:
      - "3001:80"
    depends_on:
      - api
    networks:
      - app-network
    
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf

volumes:
  mysql-data:
    driver: local

networks:
  app-network:
    driver: bridge

secrets:
  mysql_root_password:
    file: ./docker/secrets/mysql_root_password.sample
  spring_datasource_password:
    file: ./docker/secrets/spring_datasource_password.sample

configs:
  nginx_config:
    file: ./react-client/nginx.conf
